import './app/_data/articles/index';
import './app/_data/authors/index';
import './app/_data/books/index';
import './app/_data/columns/index';
import './app/_data/news/index';
import './app/_data/partners/index';
import './app/_data/threads/index';
import './app/_data/resources/index';
import './app/_data/showcases/index';
